### PR TITLE
Release 0.14.0 announcement

### PR DESCRIPTION
**Pull request by veelenga**
Rendered: https://github.com/crystal-ameba/crystal-ameba.github.io/blob/release-v0.14.0/source/_posts/release-v0.14.0.md

* [x] document new lint rules
* [x] document new performance rules
* [x] document new style rules
* [ ] https://github.com/crystal-ameba/ameba/pull/191
* [ ] https://github.com/crystal-ameba/ameba/pull/179
* [ ] https://github.com/crystal-ameba/ameba/pull/181
* [ ] https://github.com/crystal-ameba/ameba/pull/200
* [ ] https://github.com/crystal-ameba/ameba/pull/203

### CODE REVIEW

**Comment by veelenga** [comment]
@Sija would you mind documenting https://github.com/crystal-ameba/ameba/pull/179 and https://github.com/crystal-ameba/ameba/pull/181 as part of the announcement?

**Comment by Sija** [comment]
@veelenga Will do that l8r today or tmrw if that's ok with u.

**Comment by Sija** [comment]
@veelenga I'd also add https://github.com/crystal-ameba/ameba/pull/200 and https://github.com/crystal-ameba/ameba/pull/203 to the mix

**Comment by veelenga** [comment]
Good catch. Added to the description. Thanks.

**Comment by veelenga** [comment]
I am going to merge this as is since it provides at least some important changes (like changing struct to class etc.). Anyway, not all features are required to be announced :)

**Pull request merged**
